[build]
  publish = "."

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-minify-html"
  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseWhitespace = true
    
[build]
  publish = "/"
  command = ""

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200



