[build]
  publish = "."

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[plugins]]
  package = "netlify-plugin-minify-html"
  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseWhitespace = true


